name: Security Scan

on:
  push:
    branches:
      - '*'
permissions:
  contents: read
  security-events: write

jobs:
  security:
    name: Run Security Scans (Trivy + Bandit + ZAP)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit

      - name: Instalar jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # ---------------------- TRIVY ----------------------
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          limit-severities-for-sarif: false
          output: 'trivy-results.sarif'

    

      - name: Upload Trivy SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      # ---------------------- BANDIT ----------------------
      - name: Run Bandit scan
        run: |
          bandit -r . -f json -o bandit.json || true

      - name: Convert Bandit JSON to SARIF
        run: |
          python scripts/bandit_to_sarif.py

      - name: Upload Bandit SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit-results.sarif


      - name: Start Django development server
        run: |
          python manage.py migrate 
          python manage.py runserver &
        env:
          SECRET_KEY: ${{ secrets.DJANGO_PROD_SECRET_KEY }}


      - uses: actions/checkout@v3
      
      # O scan do ZAP agora pode se conectar ao servidor iniciado
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://127.0.0.1:8000"
          docker_name: ghcr.io/zaproxy/zaproxy:stable
          sarif_output: zaproxy.sarif
        continue-on-error: true
        
      - name: Stop Django development server
        run: |
          # É crucial garantir que o servidor seja parado
          pkill -f "python manage.py runserver"